<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<Authors>Infi</Authors>
		<Version>1.0.8.0</Version>
		<PackageProjectUrl>https://github.com/Infiziert90/EventyCN</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="images\icon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>
